# Generated by Django 5.0.6 on 2024-06-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API_001_Productos', '0001_initial'),
        ('API_006_Locales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_006_Locales.local')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_001_Productos.producto')),
            ],
        ),
    ]
